version: "3.3"
services:
  api:
    image: python:3.8-buster
    build:
      context: ../../backend
      dockerfile: $PWD/infrastructure/dev/Dockerfile
    command: ./manage.py runserver 0.0.0.0:8000
    entrypoint: /infrastructure/dev/wait-for-postgres.sh
    volumes:
      - ../../backend:/code
      - ../../infrastructure:/infrastructure
      - log_data:/var/log/
      - tmp_data:/tmp
    ports:
      - 8000:8000
    env_file:
      - ./config.env
    depends_on:
      - postgres
  app:
    image: node:12.13
    volumes:
      - ../../frontend/app:/code:delegated
      - app_node_modules:/code/node_modules
    working_dir: /code
    env_file:
      - ./config.env
    environment:
      - PORT=4200
    command: yarn start
    ports:
      - 4200:4200
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432


volumes:
  log_data:
  tmp_data:
  postgres_data:
  app_node_modules:
